version: '2'

services:

  discovery:
    image: 'communicator-discovery:latest'
    container_name: communicator-discovery
    command: mvn spring-boot:run
    ports:
      - "8761:8761"

  gateway:
    image: 'communicator-gateway:latest'
    container_name: communicator-gateway
    command: mvn spring-boot:run
    ports:
      - "9000:9000"
        
  chat-service:
    image: 'chat-service:latest'
    container_name: chat-service
    depends_on:
      - chat-service-db
    command: mvn spring-boot:run
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:mongo@db:5464/messages

  chat-service-db:
    image: 'mongo:5.0'
    container_name: chat-service-db
    ports:
      - "5464:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=messages

  websocket-service:
    image: 'websocket-service:latest'
    container_name: websocket-service
    command: mvn spring-boot:run
    ports:
      - "9010:9010"

  dispenser-service:
    image: 'dispenser-service:latest'
    container_name: dispenser-service
    depends_on:
      - dispenser-service-db
    command: mvn spring-boot:run
    ports:
      - "9040:9040"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:mongo@db:5564/connections

  dispenser-service-db:
    image: 'mongo:5.0'
    container_name: dispenser-service-db
    ports:
      - "5564:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kereq
      - MONGO_INITDB_ROOT_PASSWORD=kereq
      - MONGO_INITDB_DATABASE=connections