spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
    config:
      name: gateway
      uri: http://localhost:8081
    main:
      web-application-type: reactive
  rabbitmq:
    password: kereq
    port: '5672'
    addresses: 127.0.0.1
    username: kereq
  config:
    import: 'configserver:http://root:s3cr3t@localhost:8888'
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
