spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${frontend.url}"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: websocket
          uri: lb://websocket-service
          predicates:
            - Path=/ws/**
        - id: chat
          uri: lb://chat-service
          predicates:
            - Path=/chat/**
    main:
      web-application-type: reactive
